# Generated by Django 5.1.3 on 2024-12-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('shortened_url', models.CharField(blank=True, max_length=10, unique=True)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
    ]
