# Generated by Django 5.1.3 on 2024-12-04 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 11, 45, 54, 579867, tzinfo=datetime.timezone.utc)),
        ),
    ]
