# Generated by Django 5.1.3 on 2024-12-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_link_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='expiration_date',
        ),
    ]
